// Local QA only. Neither this server nor the harness is included in dist.
import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const root=resolve('dist');
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2','.txt':'text/plain'};
const harness=(url)=>{
 const w=Number(url.searchParams.get('width')||390),h=Number(url.searchParams.get('height')||844);
 const full=url.searchParams.has('full'),nojs=url.searchParams.has('nojs');
 return `<!doctype html><html><head><title>SFN local responsive check</title><style>html,body{margin:0;background:#e2e4de;font:14px system-ui}iframe{display:block;border:0;transform-origin:top left}#metrics{position:fixed;right:6px;bottom:6px;background:white;padding:6px;z-index:99;font:11px monospace}</style></head><body><iframe title="SFN preview" width="${w}" height="${h}" ${nojs?'sandbox="allow-same-origin"':''} src="/"></iframe><output id="metrics"></output><script>const f=document.querySelector('iframe');function fit(){const scale=Math.min(1,innerWidth/${w});f.style.transform='scale('+scale+')';document.body.style.height=(parseFloat(f.style.height||'${h}')*scale)+'px';}f.onload=()=>{if(${full})f.style.height=f.contentDocument.documentElement.scrollHeight+'px';fit();const d=f.contentDocument;document.querySelector('output').textContent=JSON.stringify({viewport:${w},height:${h},scrollWidth:d.documentElement.scrollWidth,overflow:d.documentElement.scrollWidth>${w},main:!!d.querySelector('main'),images:[...d.images].map(i=>({loaded:i.complete&&i.naturalWidth>0}))});};onresize=fit;fit();</script></body></html>`;
};
createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/__qa'){res.setHeader('Content-Type','text/html');res.end(harness(u));return;}let file=resolve(root,'.'+decodeURIComponent(u.pathname));if(!file.startsWith(root+'/')&&file!==root){res.statusCode=403;res.end();return;}if((await stat(file)).isDirectory())file=resolve(file,'index.html');res.setHeader('Content-Type',types[extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(await readFile(file));}catch{res.statusCode=404;res.setHeader('Content-Type','text/html');res.end(await readFile(resolve(root,'404.html')));}}).listen(4173,'0.0.0.0',()=>console.log('Production QA ready on port 4173'));
